version: '3.8'

services:
  maven-version-mcp-server:
    build: .
    container_name: maven-version-mcp-server
    ports:
      - "8081:8081"  # Metrics port
      - "8082:8082"  # Health check port
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    environment:
      - MCP_LOG_LEVEL=INFO
      - MCP_ENABLE_METRICS=true
      - MCP_ENABLE_HEALTH_CHECK=true
      - MCP_STRUCTURED_LOGGING=true
      - MCP_LOG_TO_FILE=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - maven-version-mcp-server
    restart: unless-stopped
    profiles:
      - production
